version: "3"
services:
  mongo:
    image: mongo:latest
    restart: on-failure
  bot:
    # build from scratch or use my image
    build:
      context: .
    # image: alikhil/tic-tac-toe-telegram-bot:0.1
    environment:
      TOKEN: <6511014299:AAEIdpFOs818gKhuLYMVeFnd5zSWTGkZmM8>
  
    restart: on-failure
